/*
 * WhenStatementParser.h
 *
 *  Created on: Sep 20, 2017
 *      Author: arthur moua
 */

#ifndef WCI_FRONTEND_PASCAL_PARSERS_WHENSTATEMENTPARSER_H_
#define WCI_FRONTEND_PASCAL_PARSERS_WHENSTATEMENTPARSER_H_





#endif /* WCI_FRONTEND_PASCAL_PARSERS_WHENSTATEMENTPARSER_H_ */
